FROM gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.1

CMD ["--address=0.0.0.0", "--port=3307", "--credentials-file=/jai-dev-mlconsole-poc-2ec1f3eb567b.json", "mlconsole-poc:us-central1:jai-dev-sql"]
