# Stage 1: Build a helper image with bash
FROM debian:bullseye-slim as builder

RUN apt-get update && apt-get install -y bash

# Stage 2: Final image
FROM gcr.io/cloud-sql-connectors/cloud-sql-proxy

# Copy bash from the builder stage
COPY --from=builder /bin/bash /bin/bash
CMD ["--address=0.0.0.0", "--port=3307", "--credentials-file=/application_default_credentials.json", "gcloud-hands-on-417608:us-central1:vikesh-timbba-db"]
